application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000

spring:
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:ss
    driver-class-name: org.h2.Driver
    username:
    password:

server:
  port: 8090

logging:
  level:
    web: trace
#    root: trace